// <auto-generated />
using System;
using Infraestructure.Persistence.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(RecetasContext))]
    [Migration("20230915230648_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CategoriasRecetaConfig", b =>
                {
                    b.Property<int>("CategoriaRecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaRecetaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaRecetaId");

                    b.ToTable("CategoriasReceta", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Dificultad", b =>
                {
                    b.Property<int>("DificultadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DificultadId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DificultadId");

                    b.ToTable("Dificultad", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.IngredienteReceta", b =>
                {
                    b.Property<int>("IngredienteRecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredienteRecetaId"));

                    b.Property<int>("IngredienteId")
                        .HasColumnType("int");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.HasKey("IngredienteRecetaId");

                    b.HasIndex("RecetaId");

                    b.ToTable("IngredientesReceta", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Paso", b =>
                {
                    b.Property<int>("PasosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PasosId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PasosId");

                    b.HasIndex("RecetaId");

                    b.ToTable("Pasos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PromedioPuntaje", b =>
                {
                    b.Property<int>("PromedioPuntajeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromedioPuntajeId"));

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PromedioPuntajeId");

                    b.HasIndex("RecetaId")
                        .IsUnique();

                    b.ToTable("PromedioPuntajes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Receta", b =>
                {
                    b.Property<Guid>("RecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaRecetaId")
                        .HasColumnType("int");

                    b.Property<int>("DificultadId")
                        .HasColumnType("int");

                    b.Property<string>("FotoReceta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<TimeSpan>("TiempoPreparacion")
                        .HasColumnType("time");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("RecetaId");

                    b.HasIndex("CategoriaRecetaId");

                    b.HasIndex("DificultadId");

                    b.ToTable("Recetas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.IngredienteReceta", b =>
                {
                    b.HasOne("Domain.Entities.Receta", "Receta")
                        .WithMany("IngredentesReceta")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Domain.Entities.Paso", b =>
                {
                    b.HasOne("Domain.Entities.Receta", "Receta")
                        .WithMany("Pasos")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Domain.Entities.PromedioPuntaje", b =>
                {
                    b.HasOne("Domain.Entities.Receta", "Receta")
                        .WithOne("PromedioPuntaje")
                        .HasForeignKey("Domain.Entities.PromedioPuntaje", "RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Domain.Entities.Receta", b =>
                {
                    b.HasOne("Domain.Entities.CategoriasRecetaConfig", "CategoriaReceta")
                        .WithMany("Recetas")
                        .HasForeignKey("CategoriaRecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Dificultad", "Dificultad")
                        .WithMany("Recetas")
                        .HasForeignKey("DificultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaReceta");

                    b.Navigation("Dificultad");
                });

            modelBuilder.Entity("Domain.Entities.CategoriasRecetaConfig", b =>
                {
                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("Domain.Entities.Dificultad", b =>
                {
                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("Domain.Entities.Receta", b =>
                {
                    b.Navigation("IngredentesReceta");

                    b.Navigation("Pasos");

                    b.Navigation("PromedioPuntaje")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
